---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

1.2.1

```{r}
meteorite_landings_clean <-
  read_csv("meteorite_landings_clean.csv")
```


```{r}
meteorite_landings_clean
```


1.2.2

```{r}
meteorite_landings_clean %>% 
  arrange(desc(mass_in_grams)) %>% 
  head(10)

```


1.2.3

```{r}
avg_mass_fell <-
meteorite_landings_clean %>% 
  filter(fall_status == "Fell") %>% 
  summarise(avg_mass_fell = mean(mass_in_grams, na.rm = TRUE))
```


```{r}
avg_mass_found <-
meteorite_landings_clean %>% 
  filter(fall_status == "Found") %>% 
  summarise(avg_mass_found = mean(mass_in_grams, na.rm = TRUE))
```


1.2.4

```{r}
meteorite_landings_clean %>% 
  filter(year <= 2000) %>% 
  nrow()
```















































































































































































































































































































































































































































































































































